version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

    web:
        build: .
        volumes:
            - .:\D\DEV\APP\Docker
        ports:
            - "8000:8000"
